title = "Template file containing all configuration for debug"

[system]
teamFoundationCollectionUri = "" # URL of the Azure DevOps Server/Services. Example: http://192.168.1.32/DefaultCollection/
teamProjectId = "" # Example: f0000d00-0a0d-0c00-b00a-00a00000a000
teamProject = "" # Example: MyTeamProject

[logging]
logLevel = "" # Example: "DEBUG", "INFO", "WARNING", "ERROR"

[build]
sourceBranchName = "" # Example: main
definitionName = "" # Example: pipeline1
buildId = 0 # Example: 20

[octane]
serviceConnectionName = "" # Example: "Octane"
workspaces = [] # Example: 1002,1003
[octane.auth]
parameters = "" # Example 1: { username: "someuser@somecompany.com", password: "pwd"}
                # Example 2: { accessToken: "000fc0a0e0afd000fc0ed0b0000f0b0e000b000e"}
scheme = "" # Example 1: username; Example 2: PersonalAccessToken


[endpoint]
url = "" # Example: "http://localhost:9090/dev/ui/?p=1001/1002"
octaneInstanceId = "" # Example octane123
azurePersonalAccessToken = "" # Example ccccccccccccccc0cccc0cc00occccccc0cc0cccccc0cccccc0c

[repository]
repositoryConnection = "" # Example: "gitHub"
type = "" # Example: "INTERNAL" or "GIT"
[repository.auth]
parameters = "" # Example 1: { username: "someuser@somecompany.com", password: "pwd"}
                # Example 2: { accessToken: "000fc0a0e0afd000fc0ed0b0000f0b0e000b000e"}
scheme = "" # Example 1: username; Example 2: PersonalAccessToken

[node]
[node.proxy]
http = ""
https = ""

